# 开发环境
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myblog?serverTimezone=GMT%2B8
    username: root
    password: 971211
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      每次匹配同步 数据库表 和 实体类
      ddl-auto: update
#      显示sql
    show-sql: true
  #  日志配置
logging:
#  全局日志级别
  level:
    root: info
#  指定项目日志级别
    com.xxh: debug
#    输出日志目录 默认为10M切分
  file: log/blog-dev.log